[s390x] syscall: generate ztypes using unsigned char
The s390x syscall API in gccgo (mainly) uses unsigned chars, so
we can't use signed chars without breaking compatibility with
gccgo.

Exception: currently the RawSockaddr and RawSockaddrUnix structs
assume signed chars in gccgo. On other platforms only
RawSockaddrUnix is forced to use signed chars so we copy that
convention. This should mean that only RawSockaddr differs from
gccgo.